# render.yaml

services:
  - type: web
    name: second-brain-backend
    env: node
    plan: free
    region: oregon
    buildCommand: |
      npm install
      npm run build
    startCommand: node dist/index.js
    branch: main
    runtime: node
    nodeVersion: 18
    autoDeploy: true
    buildFilter:
      paths:
        - src/**
        - package.json
        - package-lock.json
        - tsconfig.json
